#!/usr/bin/env node
const {loader, warnings, resolve, spawnSync} = require('./ganesha-run')

const [node, ganesha, ...argv] = process.argv
process.argv = [node, ...argv] // remove Ganesha script

const { status } = spawnSync(node, [

  // hide the experimental loader warning
  '-r', warnings,

  // https://nodejs.org/api/cli.html#--experimental-loadermodule
  '--experimental-loader', loader,

  // https://nodejs.org/api/cli.html#--experimental-specifier-resolutionmode
  '--experimental-specifier-resolution=node',

  ...argv

], { stdio: 'inherit' })

process.exit(status)
