#!/usr/bin/env node
const loader = require.resolve('@ganesha/node/loader.mjs')

const [node, ganesha, ...argv] = process.argv
process.argv = [node, ...argv] // remove Ganesha

const crossSpawn = require('cross-spawn')
const {resolve} = require('path')
const main = crossSpawn.sync(node, [
  '-r', require.resolve('@ganesha/node/warning.cjs'),
  '--experimental-loader', loader,
  ...argv
], { stdio: 'inherit' })

process.exit(main.status)
