name: CI
on:
  push:
    branches:
      - develop
      - prerelease
  pull_request: {}
  workflow_dispatch: {}

jobs:

  sanity-check:
    name: Check that the library can be installed
    runs-on: ubuntu-latest
    steps:
      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.3

      - name: Create minimal project
        run: |
          ls -al
          echo '{}' > package.json
          export COMMIT=$(git rev-parse HEAD)
          pnpm add github:hackbg/ganesha#$COMMIT
          ls -al node_modules
          pnpm i
          node_modules/.bin/ganesha-node

  test:
    name: Run tests & coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16, 17]
    steps:

      - name: Fetch sources
        uses: actions/checkout@v2
        with: { submodules: recursive }

      - name: Setup Node
        uses: actions/setup-node@v2
        with: { node-version: ${{ matrix.node }} }

      - name: Install PNPM and deps
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.3
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Run tests
        run: pnpm -w dev test all

      #- name: Coverage
        #run: pnpm run coverage

      #- uses: codecov/codecov-action@v2 
        #with: 
          #token: ${{ secrets.CODECOV_TOKEN }}
          #
