name: CI
on:
  push:
    branches:
      - develop
      - prerelease
  pull_request: {}
  workflow_dispatch: {}

jobs:
  test:
    name: Run tests & Coverage
    runs-on: ubuntu-latest
    steps:

      - name: Fetch sources
        uses: actions/checkout@v2
        with: { submodules: recursive }

      - name: Setup Node
        uses: actions/setup-node@v2
        with: { node-version: '14' }

      - name: Install PNPM and deps
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.3
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Run tests
        run: pnpm -w dev test all

      #- name: Coverage
        #run: pnpm run coverage

      #- uses: codecov/codecov-action@v2 
        #with: 
          #token: ${{ secrets.CODECOV_TOKEN }}
          #
