on: [push, pull_request]
name: Run tests
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:

      - name: Fetch sources
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with: { node-version: '14' }

      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.3
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Run tests
        run: pnpm test
